#!/bin/bash

addgroup jjs
adduser --system --ingroup jjs --home /var/lib/jjs --disabled-login jjs

su -c 'jjs-mkroot /var/lib/jjs /usr/share/jjs/example-config' -s "$SHELL" jjs

# TODO: proper systemd unit for jjs
