#ifndef JTL_MAIN
#define JTL_MAIN
#include <cstdio>
#include "testgen.h"



testgen::Input init_testgen();


/// return type for functions that do not return
enum class Uninhabited {
};

/// utility functions checks than only whitespace chars are remaining in file
bool is_file_eof(FILE* f);

#ifdef __GNUC__
#define FORMAT_FN(x) __attribute__ (( format( printf, x, x+1 ) ))
#else
#define FORMAT_FN(x)
#endif

namespace checker {

    void comment(const char* format, ...) FORMAT_FN(1);

    void sol_scanf(const char* format, ...) FORMAT_FN(1);

    void corr_scanf(const char* format, ...) FORMAT_FN(1);

    void test_scanf(const char* format, ...) FORMAT_FN(1);

    void check_sol_eof();

    void check_corr_eof();

    void check_test_eof();


    struct CheckerInput {
        /// Contestant's solution answer
        FILE* sol_answer;
        /// Correct answer (answer generated by primary solution), if requested by problem config. Otherwise, refers to /dev/null
        FILE* corr_answer;
        /// Test data
        FILE* test;
    };

    CheckerInput init();

    /// Reads next char sequence, followed by whitespace
    char* next_token(FILE* f);

    enum class Outcome {
        /// Checker couldn't recognize answer
            PRESENTATION_ERROR,
        /// Answer was wrong
            WRONG_ANSWER,
        /// Correct answer
            OK,
        /// Checker is incorrect
        /// for example, contestant provided more optimal answer than jury
            CHECKER_LOGIC_ERROR,
    };

/// Checker exits using this function
/// If checker simply exits with e.g. exit(0) protocol will be broken and internal judging error will be diagnosed
    Uninhabited finish(Outcome outcome);
}

#endif