/*
 * JJS main API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiVersion {
    /// MAJOR component
    #[serde(rename = "major")]
    pub major: i32,
    /// MINOR component
    #[serde(rename = "minor")]
    pub minor: i32,
}

impl ApiVersion {
    pub fn new(major: i32, minor: i32) -> ApiVersion {
        ApiVersion { major, minor }
    }
}
