/*
 * JJS main API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Contest {
    /// Configured by human, something readable like 'olymp-2019', or 'test-contest'
    #[serde(rename = "id")]
    pub id: String,
    /// E.g. \"Berlandian Olympiad in Informatics. Finals. Day 3.\"
    #[serde(rename = "title")]
    pub title: String,
}

impl Contest {
    pub fn new(id: String, title: String) -> Contest {
        Contest { id, title }
    }
}
