/*
 * JJS main API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Problem {
    /// Problem name
    #[serde(rename = "name")]
    pub name: String,
    /// Problem relative name (aka problem code) as contestants see. This is usually one letter or something similar, e.g. 'A' or '3F'.
    #[serde(rename = "rel_name")]
    pub rel_name: String,
    /// Problem title as contestants see, e.g. \"Find max flow\".
    #[serde(rename = "title")]
    pub title: String,
}

impl Problem {
    pub fn new(name: String, rel_name: String, title: String) -> Problem {
        Problem {
            name,
            rel_name,
            title,
        }
    }
}
