/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Run {
    #[serde(rename = "contest_id")]
    pub contest_id: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "problem_id")]
    pub problem_id: String,
    #[serde(rename = "toolchain_id")]
    pub toolchain_id: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
}

impl Run {
    pub fn new(
        contest_id: String,
        id: String,
        problem_id: String,
        toolchain_id: String,
        user_id: String,
    ) -> Run {
        Run {
            contest_id,
            id,
            problem_id,
            toolchain_id,
            user_id,
        }
    }
}
