/*
 * JJS main API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunSimpleSubmitParams {
    /// Base64-encoded source text
    #[serde(rename = "code")]
    pub code: String,
    /// Contest where run is submitted
    #[serde(rename = "contest")]
    pub contest: String,
    /// Problem name, relative to contest
    #[serde(rename = "problem")]
    pub problem: String,
    /// Toolchain to use when judging this run
    #[serde(rename = "toolchain")]
    pub toolchain: String,
}

impl RunSimpleSubmitParams {
    pub fn new(
        code: String,
        contest: String,
        problem: String,
        toolchain: String,
    ) -> RunSimpleSubmitParams {
        RunSimpleSubmitParams {
            code,
            contest,
            problem,
            toolchain,
        }
    }
}
