/*
 * JJS main API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunPatch {
    /// Queue for judging again
    #[serde(rename = "rejudge", skip_serializing_if = "Option::is_none")]
    pub rejudge: Option<bool>,
    /// New score (useful for custom judging)
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<i32>,
}

impl RunPatch {
    pub fn new() -> RunPatch {
        RunPatch {
            rejudge: None,
            score: None,
        }
    }
}
