/*
 * JJS main API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimpleAuthParams {
    /// Login
    #[serde(rename = "login")]
    pub login: String,
    /// Password
    #[serde(rename = "password")]
    pub password: String,
}

impl SimpleAuthParams {
    pub fn new(login: String, password: String) -> SimpleAuthParams {
        SimpleAuthParams { login, password }
    }
}
