/*
 * JJS main API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// UUID of this user.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "login")]
    pub login: String,
}

impl User {
    pub fn new(id: String, login: String) -> User {
        User { id, login }
    }
}
