/*
 * JJS main API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCreateParams {
    /// List of groups new user should belong to
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<String>>,
    /// Login (must be unique)
    #[serde(rename = "login")]
    pub login: String,
    /// Password (no strength validation is performed)
    #[serde(rename = "password")]
    pub password: String,
}

impl UserCreateParams {
    pub fn new(login: String, password: String) -> UserCreateParams {
        UserCreateParams {
            groups: None,
            login,
            password,
        }
    }
}
