/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationError {
    #[serde(rename = "loc")]
    pub loc: Vec<String>,
    #[serde(rename = "msg")]
    pub msg: String,
    #[serde(rename = "type")]
    pub _type: String,
}

impl ValidationError {
    pub fn new(loc: Vec<String>, msg: String, _type: String) -> ValidationError {
        ValidationError { loc, msg, _type }
    }
}
